parameters:
#    symfonyse_author.example.class: Symfonyse\AuthorBundle\Example

services:
  symfonyse.author.content_provider:
    class: Symfonyse\CoreBundle\ContentProvider\CoreContentProvider
    arguments: [~ , 'md']