parameters:
#    symfonyse_author.example.class: Symfonyse\AuthorBundle\Example

services:
  symfonyse.author.content_provider:
    class: Symfonyse\AuthorBundle\ContentProvider\ContentProvider
    arguments: [~ , 'md']
    calls:
      - [setContentProviders, [[@symfonyse.blog.content_provider, @symfonyse.video.content_provider, @symfonyse.event.content_provider]]]
