homepage:
    pattern:  /
    defaults: { _controller: SymfonyseContentBundle:Default:homepage }

page:
  pattern:  /page/{permalink}
  defaults: { _controller: SymfonyseContentBundle:Page:page }
  requirements:
    permalink:  .+
