parameters:
#    symfonyse_content.example.class: Symfonyse\ContentBundle\Example

services:
#    symfonyse_content.example:
#        class: %symfonyse_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
