parameters:
#    symfonyse_content.example.class: Symfonyse\ContentBundle\Example

services:
  symfonyse.content.content_provider:
    class: Symfonyse\CoreBundle\ContentProvider\CoreContentProvider
    arguments: [~ , 'md']