

event_index:
  pattern:  /index
  defaults: { _controller: SymfonyseEventBundle:Event:index }


event:
  pattern:  /{permalink}
  defaults: { _controller: SymfonyseEventBundle:Event:entry }
  requirements:
    permalink:  "[0-9]+/.+"