parameters:
#    symfonyse_event.example.class: Symfonyse\EventBundle\Example

services:
  symfonyse.event.content_provider:
    class: Symfonyse\EventBundle\ContentProvider\ContentProvider
    arguments: [~ , 'md']