parameters:
#    symfonyse_event.example.class: Symfonyse\EventBundle\Example

services:
  symfonyse.event.content_provider:
    class: Symfonyse\EventBundle\ContentProvider\FileContentProvider
    arguments: [~ , 'md']


  symfonyse.event.meetup_content_provider:
    class: Symfonyse\EventBundle\ContentProvider\MeetupContentProvider
    arguments: [@dms_meetup_api.client_factory]
