blog_index:
  pattern:  /index
  defaults: { _controller: SymfonyseBlogBundle:Blog:index }

blog:
  pattern:  /{permalink}
  defaults: { _controller: SymfonyseBlogBundle:Blog:entry }
  requirements:
    permalink:  "[0-9]+/.+"

