symfonyse_blog_index:
  pattern:  /index
  defaults: { _controller: SymfonyseBlogBundle:Blog:index }

symfonyse_blog_entry:
  pattern:  /post/{permalink}
  defaults: { _controller: SymfonyseBlogBundle:Blog:entry }
  requirements:
    permalink:  .+

symfonyse_blog_category:
  pattern:  /category/{permalink}
  defaults: { _controller: SymfonyseBlogBundle:Category:entry }
  requirements:
    permalink:  .+
