parameters:
#    symfonyse_tag.example.class: Symfonyse\TagBundle\Example

services:
  symfonyse.tag.content_provider:
    class: Symfonyse\CoreBundle\ContentProvider\CoreContentProvider
    arguments: [~ , 'md']