

video_index:
  pattern:  /index
  defaults: { _controller: SymfonyseVideoBundle:Video:index }

video:
  pattern:  /{permalink}
  defaults: { _controller: SymfonyseVideoBundle:Video:entry }
  requirements:
    permalink:  .+
