security:
  providers:
    in_memory:
      memory:
        users:
          user:  { roles: [ 'ROLE_USER' ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    secured:
      pattern:  ^/*
      anonymous: ~

  access_control:
    - { path: .*/esi/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

