parameters:
  assetic.value_supplier.class: Symfonyse\CoreBundle\Assetic\CustomValueSupplier

services:
  symfonyse.core.twig.intl_extension:
    class: Twig_Extensions_Extension_Intl
    tags:
        - { name: twig.extension }


