parameters:
#    symfonyse_core.example.class: Symfonyse\CoreBundle\Example

services:
  symfonyse.core.twig.intl_extension:
    class: Twig_Extensions_Extension_Intl
    tags:
        - { name: twig.extension }


